#pragma once
#include <algorithm>
#include <array>
#include <chrono>
#include <concurrent_vector.h>
#include <concurrent_queue.h>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <mutex>
#include <numeric>
#include <ppl.h>
#include <queue>
#include <random>
#include <stack>
#include <string>
#include <sstream>
#include <thread>
#include <unordered_map>
#include <vector>
#define NOMINMAX
#include <windows.h>
#include "API.h"
